### PR TITLE
Release 2 docs

### PR DESCRIPTION
**Pull request by alvarolopez**

### CODE REVIEW

**Comment by alvarolopez** [comment]
Hi @vykozlov please check if everything is OK and merge it, please.

**Comment by IgnacioHeredia** [comment]
@vykozlov please wait before merging to master since have some final changes that are not yet committed. I will commit them during this afternoon. Thanks.

**Comment by IgnacioHeredia** [comment]
@vykozlov You can proceed now with the merge!

**Comment by vykozlov** [comment]
sorry, after fixes need other fixes :-) should finish today

**Comment by alvarolopez** [comment]
Hi Valentin.

I would like to close it by today.

Any chance we can merge it before noon?

**Comment by vykozlov** [comment]
yes. finalizing last bits

**Comment by vykozlov** [comment]
It seems I can't no longer merge. Closing and creating new pull request.

**Pull request closed without merging**
